name: Docker Build - DevCell

on:
    workflow_dispatch:
        inputs:
            DEV_CELL_SUFFIX:
                description: 'Dev cell suffix'
                required: true
                default: ''

jobs:
    call-reusable-workflow:
        uses: ./.github/workflows/docker-build-abstract.yml
        with:
            AWS_REGION: "us-east-1"
            AWS_ACCOUNT_ID: "975050354766"
            DEV_CELL_SUFFIX: ${{ github.event.inputs.DEV_CELL_SUFFIX }}
        permissions:
            id-token: write
            contents: read
